### ISSUE TITLE
After installing sample data, create Reseller Org results in Operation Failed

### ISSUE THREAD

**Issue by farmakiG** [servicecatalog/oscm#1112] opened 2020-11-02 10:19 UTC
**Version Info**
Current master with OSCM_Pull_and_start.

**Describe the bug**
Creation of an organization with the "Reseller" role results in Operation Failed.

**How to Reproduce**
1. Login as Operator
2. Go to the "Create Organization" page.
3. Fill-in the mandatory data for the organization to create (e.g. user id: reseller).
4. Select the "Reseller" Organization role.

**Observed behavior**
Operation Failed appears.

**Expected behavior**
The reseller organization is created successfully.

**Screenshots**
![Screenshot_2020-11-02](https://user-images.githubusercontent.com/49904723/97872560-8868fd00-1d16-11eb-8138-8288f13efd84.png)

**Log file**
[system.log](https://github.com/servicecatalog/oscm/files/5475258/system.log)

**Additional context**
Any other context about the problem here.

**Comment by GoebelL** [comment] 2020-11-02 17:42
This is reproducible when installing with sample data. Seems that add database is created from inconsistent state.
Logs show: Batch entry 0 insert into OrganizationToRoleHistory (invocationDate, modDate, modType, modUser, objKey, objVersion, organizationRoleTKey, organizationTKey, *TKEY*) values ('2020-11-2 16:38:46.370000 +0:0:0', '2020-11-2 16:38:46.370000 +0:0:0', 'ADD', '1000', 12002, 0, 7, 12001, *12001*) was aborted. 

Appears since the tkey 12001 record already exists. I could figure out what is wrong in the sample bss database dump. However, it looks suspicious to me, that there is a [DELETE entry in the organizationtorolehistory table](https://github.com/servicecatalog/oscm-dockerbuild/blob/master/oscm-initdb/templates/sample.sql.core.template#L177).

@cworf91 
I suggest to install a v19.0 database with sample data and on top create the reseller model from scratch and with a a clean history. Avoid any creation, modification or deletion by mistake, i.e. like unnecessary adding and revoking of unneeded roles etc.

**Comment by GoebelL** [comment] 2020-11-03 12:57
Fixed with https://github.com/servicecatalog/oscm-dockerbuild/pull/284.

**Closed as completed by GoebelL** 2020-11-03 12:57 UTC
Labels: bug, P1
