### ISSUE TITLE
Issues with accented characters

### ISSUE THREAD

**Issue by fabiorauber** [servicecatalog/oscm#247] opened 2019-03-13 13:39 UTC
**Version Info**
v17.10

**Describe the bug**
When saving strings (for instance, in Organization names or Addresses) with accented characters (like ã, õ, ô), the special character is being replaced by interrogation marks ("??"). 

**How to Reproduce**
1. Create and organization or customer with an accented character in the name
2. Visualize the organization name in the User Interface (administrative or marketplace)
3. See the name with the accented characters replaced by "??"

**Observed behavior**
Special characters not being correctly saved.

**Expected behavior**
Special characters being saved correctly, as was happening before version v17.9.

**Comment by GoebelL** [comment] 2019-03-14 00:36
@fabiorauber 
There hasn't been any change recently. I rather believe you selected a locale for the created organization which's browser language provided charcacter set doesn't supply for those non-ASCII characters. Could this be?

**Comment by fabiorauber** [comment] 2019-03-18 18:22
Actually, when I set the language to English, it works. When I configure an user account to use Portuguese (ISO code pt), and then save a new Organization using a profile that uses Portuguese as the language, the special characters are not being correctly saved, apparently.

PS: my current Browser is configured to use Portuguese (UTF-8) as default language.

**Comment by farmakiG** [comment] 2019-05-28 12:56
Close as duplicate of issue #311.

**Closed as completed by farmakiG** 2019-05-28 12:56 UTC
Labels: bug, P3
