### ISSUE TITLE
aws cannot be used since connection not possible 

### ISSUE THREAD

**Issue by ghost** [servicecatalog/oscm#70] opened 2018-01-18 08:22 UTC
[Build] 17.6 2018/17/02

[Steps to reproduce]
1. import and publish aws service
2. try to subscribe

[Expected result]
subscription possible

[Observed result]
Connect to ec2.eu-west-1.amazonaws.com:443 [ec2.eu-west-1.amazonaws.com/54.239.39.130] failed: Connection refused (Connection refused)

[Details]
It seems that no connection is possible from app container. base machine of docker can connect to internet. I also looked for a way to specify a proxy in the environment files .env and var.env . But this
does not seem possible. 
Therefore aws is not usable at the moment.

**Comment by shimizuf** [comment] 2018-01-18 09:01
Clarification: This is in an environment where internet connections are only possible via HTTP proxy. Proxy functionality for the application is not implemented yet. See also servicecatalog/oscm-dockerbuild/issues/37

**Comment by grubskim** [comment] 2018-02-01 15:22
Hello,

I have set three environmental variables for tomee proxy in file /opt/apache-tomee/bin/setenv.sh (in both core and app containers). The issue is, i cannot ping ec2.eu-west-1.amazonaws.com, even from the Jenkins node. The proxy is set there, and i am only able to ping localhost, and other Jenkins nodes. Please advise if there is anything else related to the tomee configuration, or is it a node network configuration issue.

**Comment by shimizuf** [comment] 2018-02-02 06:48
@grubskim By "ping", do you mean an actual ICMP echo request with the ping command? I believe that the firewall does not allow ping directly to to internet. So I fear the only way to really test this is to have the application connect to the internet via the proxy.

**Comment by grubskim** [comment] 2018-02-02 09:09
Sorry, I don't know, I just typed 'ping ec2.eu-west-1.amazonaws.com'. I can ping it from my machine without proxy.

**Comment by shimizuf** [comment] 2018-02-02 09:13
Is your machine in a different network than the system which OSCM runs on? I suspect that the firewall of the network your machine is in allows ping to the internet while the firewall in front of the OSCM system does not.

**Comment by grubskim** [comment] 2018-02-02 13:16
Tried with the below properties for tomee set:
http.proxySet
https.proxySet
http.proxyHost
https.proxyHost
http.proxyPort
https.proxyPort
Unfortunately, the end result is still the same.

@shimizuf Yes, my machine is in a completely different network. Now i am not sure if the tomee proxy doesn't work, or is it a network configuration issue.

**Comment by shimizuf** [comment] 2018-02-02 15:20
If the proxy settings in setenv.sh do not work, could you try setting them in `catalina.properties`?

**Comment by grubskim** [comment] 2018-02-07 15:00
Fixed by adding correct proxy variables to tomee.

**Closed as completed by grubskim** 2018-02-07 15:00 UTC
Labels: bug, QA, P1, verified

**Comment by kolodziejczykm** [comment] 2018-02-09 15:53
Retested with TAG_DOCKER: v17.6.0-RC5. 
Was able to import, publish and subscribe to the AWS 
![awsproxy](https://user-images.githubusercontent.com/34572039/36036189-80a10d0c-0db9-11e8-868d-2fe75716e1d4.JPG)
